# Generated by Django 4.2.1 on 2023-06-05 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(max_length=100)),
                ('pilote1', models.CharField(max_length=100)),
                ('pilote2', models.CharField(max_length=100)),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('nombre_passagers_depart', models.IntegerField(blank=True, null=True)),
                ('nombre_passagers_arrivee', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('metier', models.CharField(choices=[('1', 'Hôtesse'), ('2', 'Steward'), ('3', 'Personnel navigant commercial'), ('4', 'Chef de cabine'), ('5', 'Chef de cabine principal'), ('6', 'Commandant de bord'), ('7', 'Personnel navigant technique'), ('8', 'Autre')], default='1', max_length=30)),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeroport.avion')),
            ],
        ),
    ]
