# Generated by Django 4.2.1 on 2023-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroport', '0002_alter_personnel_avion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avion',
            name='pilote1',
        ),
        migrations.RemoveField(
            model_name='avion',
            name='pilote2',
        ),
        migrations.AddField(
            model_name='avion',
            name='modele',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='metier',
            field=models.CharField(choices=[('1', 'Pilote'), ('2', 'Copilote'), ('3', 'Hôtesse'), ('4', 'Steward'), ('5', 'Personnel navigant commercial'), ('6', 'Chef de cabine'), ('7', 'Chef de cabine principal'), ('8', 'Commandant de bord'), ('9', 'Personnel navigant technique'), ('10', 'Autre')], default='1', max_length=30),
        ),
    ]
